#!/bin/bash

set -euo pipefail

RUNDIR=$1
NPROCS=$2
NCORES=$3
HOSTS=$4


RUN_DETAILS_FILES="
aerosol.formatted aerosol_lat.formatted aerosol_lon.formatted aerosol_plev.formatted
bulkdens.asc_s_0_03_0_9 bulkradii.asc_s_0_03_0_9
CAM_ABS_DATA CAM_AEROPT_DATA
CAMtr_volume_mixing_ratio.A1B CAMtr_volume_mixing_ratio.A2 
CAMtr_volume_mixing_ratio.RCP4.5 CAMtr_volume_mixing_ratio.RCP6
CAMtr_volume_mixing_ratio.RCP8.5
capacity.asc
CCN_ACTIVATE.BIN CLM_ALB_ICE_DFS_DATA CLM_ALB_ICE_DRC_DATA
CLM_ASM_ICE_DFS_DATA CLM_ASM_ICE_DRC_DATA
CLM_DRDSDT0_DATA CLM_EXT_ICE_DFS_DATA CLM_EXT_ICE_DRC_DATA
CLM_KAPPA_DATA CLM_TAU_DATA
co2_trans coeff_p.asc coeff_q.asc constants.asc
ETAMPNEW_DATA ETAMPNEW_DATA_DBL ETAMPNEW_DATA.expanded_rain
ETAMPNEW_DATA.expanded_rain_DBL
GENPARM.TBL grib2map.tbl gribmap.txt
kernels.asc_s_0_03_0_9 kernels_z.asc 
LANDUSE.TBL
masses.asc
MPTABLE.TBL
ozone.formatted ozone_lat.formatted ozone_plev.formatted
p3_lookup_table_1.dat
RRTM_DATA RRTM_DATA_DBL RRTMG_LW_DATA RRTMG_LW_DATA_DBL 
RRTMG_SW_DATA RRTMG_SW_DATA_DBL SOILPARM.TBL
termvels.asc
tr49t67
tr49t85
tr67t85
URBPARM.TBL
URBPARM_UZE.TBL
VEGPARM.TBL
wind-turbine-1.tbl
"
export PATH="/usr/lib64/openmpi/bin:$PATH"

COMPONENT=wrf

# start ssh
/usr/bin/ssh-keygen -A
echo ""| ssh-keygen -q -t rsa -N ''
cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
cat > /root/.ssh/config <<EOF
Host *
StrictHostKeyChecking no
EOF
chmod 400 /root/.ssh/config 

/usr/sbin/sshd

cd ${RUNDIR}
for f in ${RUN_DETAILS_FILES}
do
    rm -rf ./$f
    ln -sf /wrf/WRF/run/$f .
done
ln -sf /wrf/WRF/run/wrf.exe .

export OMP_NUM_THREADS=${NCORES}

time mpirun --allow-run-as-root -x OMP_NUM_THREADS \
     --hostfile ${HOSTS} -np ${NPROCS} \
     -v --display-map --mca btl self,tcp ./wrf.exe
#     --mca btl self,tcp --mca btl_tcp_if_include $iface ./wrf.exe


ls -ls wrfo*
OK_step=$?

if [ $OK_step -eq 0 ]; then
    tail rsl.error.0000
else
    echo ${COMPONENT} FAILED
    exit 444
fi
